using System.Text;
using GitVault.Core.Entities;
using GitVault.Core.Services;
using GitVault.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace GitVault.Infrastructure.Services;

public class ServingService(
    IStorageService storage,
    ICryptoService crypto,
    IGitHubContentService gitHubContent,
    IFirebaseTokenValidator firebaseValidator,
    IAppService appService,
    IMetadataService metadata,
    GitVaultDbContext db,
    ILogger<ServingService> logger) : IServingService
{
    public async Task<ServingResult> ResolveAsync(
        string publicId,
        string? authorizationHeader,
        CancellationToken ct)
    {
        if (publicId.Length < 5) return ServingResult.NotFound();

        // 1. Route via shortCode embedded in publicId — no file-table lookup needed
        var shortCode = crypto.ExtractVaultShortCode(publicId);
        var vault = await db.Vaults.FirstOrDefaultAsync(v => v.ShortCode == shortCode, ct);
        if (vault is null) return ServingResult.NotFound();

        // 2. Fetch encrypted metadata from GitHub
        var file = await metadata.GetByPublicIdAsync(publicId, ct);
        if (file is null) return ServingResult.NotFound();

        // 3. Verify the public_id was generated by this server (HMAC check)
        if (!crypto.VerifyPublicId(publicId, file.LogicalId))
        {
            logger.LogWarning("public_id HMAC verification failed for {PublicId}", publicId);
            return ServingResult.NotFound();
        }

        // 4. Private files require valid credentials
        if (file.Visibility == FileVisibility.Private)
        {
            if (!await IsAuthorizedAsync(file, authorizationHeader, ct))
                return ServingResult.Unauthorized();
        }

        // 5. Public file in public repo → 302 to CDN (zero API cost)
        if (file.Visibility == FileVisibility.Public && !vault.IsPrivate)
        {
            var blobPath = $"objects/{file.Sha256[..2]}/{file.Sha256[2..4]}/{file.Sha256}";
            var rawUrl = gitHubContent.GetRawUrl(vault.RepoFullName, vault.DefaultBranch, blobPath);
            return ServingResult.Redirect(rawUrl, file.ContentType, file.OriginalName);
        }

        // 6. Private file or private repo → stream through backend
        var contentResult = await storage.GetBlobContentAsync(file.VaultId, file.Sha256, ct);
        if (!contentResult.IsSuccess) return ServingResult.NotFound();

        return ServingResult.Stream(
            contentResult.Value!,
            file.ContentType,
            file.SizeBytes,
            file.OriginalName);
    }

    // ── Authorization ─────────────────────────────────────────────────────────

    private async Task<bool> IsAuthorizedAsync(
        FileMetadata file,
        string? authorizationHeader,
        CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(authorizationHeader)) return false;

        if (authorizationHeader.StartsWith("Bearer ", StringComparison.OrdinalIgnoreCase))
        {
            var token = authorizationHeader["Bearer ".Length..].Trim();
            var claims = await firebaseValidator.ValidateAsync(token, ct);
            if (claims is null) return false;

            return await db.Vaults.AnyAsync(
                v => v.VaultId == file.VaultId && v.UserId == claims.Uid, ct);
        }

        if (authorizationHeader.StartsWith("Basic ", StringComparison.OrdinalIgnoreCase))
        {
            try
            {
                var encoded = authorizationHeader["Basic ".Length..].Trim();
                var decoded = Encoding.UTF8.GetString(Convert.FromBase64String(encoded));
                var colon = decoded.IndexOf(':');
                if (colon < 0) return false;

                var apiKey = decoded[..colon];
                var apiSecret = decoded[(colon + 1)..];

                var app = await appService.ValidateCredentialAsync(apiKey, apiSecret, ct);
                if (app is null || !app.IsActive) return false;
                if (!app.HasScope("files:read")) return false;

                var vaultIds = app.GetVaultIds();
                if (vaultIds.Count > 0 && !vaultIds.Contains(file.VaultId)) return false;

                return true;
            }
            catch
            {
                return false;
            }
        }

        return false;
    }
}
